const express = require('express')
const router = express.Router()
const passport = require('../config/passport')
const basketball = require('./modules/basketball')
const admin = require('./modules/admin')
const upload = require('../middleware/multer')
const userController = require('../controllers/user-controller')
const basketballController = require('../controllers/basketball-controller')
const { signUpValidator, formError } = require('../middleware/validator')
const { authenticated } = require('../middleware/auth')
const { generalErrorHandler } = require('../middleware/error-handler')
router.use('/admin',admin)
router.use('/basketball',authenticated,basketball)
router.get('/register', userController.registerPage)
router.post('/register', upload.single('image'), signUpValidator, formError, userController.register)
router.get('/rank',basketballController.getRank)
router.get('/TRank',basketballController.getTRank)
router.get('/login',userController.loginPage) 
router.post('/login', passport.authenticate('local', { failureRedirect: '/login', failureFlash: true }),userController.login)
router.get('/logout', userController.logout)
router.post('/following/:userId', authenticated, userController.addFollowing)
router.delete('/following/:userId', authenticated, userController.removeFollowing)
router.get('/',(req, res) => res.redirect('/basketball/:id'))
router.use('/',generalErrorHandler)
module.exports = router